version: '3'

networks:
  prom:

volumes:
  prometheus_data:
  grafana_data:
  postgresql:
  postgresql_data:

services:
  tst-prometheus:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/tstPrometheus
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: admin
    depends_on:
      - prometheus 
      - db  
    networks:
      - prom  
  
  db:
    container_name: postgresql
    image: postgres:13.2
    environment:
      POSTGRES_DB: tstPrometheus
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgre
      - postgresql_data:/var/lib/postgre/data
    networks:
      - prom  
    

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - prom

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - prom

  dbexporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    networks:
      - prom
    depends_on:
      - db  
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin@db:5432/tstPrometheus?sslmode=disable"
  
  aletmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - 9093:9093
    networks:
      - prom
    depends_on:
      - prometheus
  
  


