
# DEFINICAO SERVIDOR DE APLICACAO
server:
    port: 8080
    
# DEFINICAO BANCO DE DADOS      
spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/tstPrometheus
        username: postgres
        password: 14062000
        
